# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: Deliver Floorp RC updates
on:
  workflow_dispatch:
    inputs:
      win-mar-url:
        type: string
        required: true
        description: Windows x86_64 complete MAR file URL
      linux-mar-url:
        type: string
        required: true
        description: Linux x86_64 complete MAR file URL
      mac-mar-url:
        type: string
        required: true
        description: macOS Universal complete MAR file URL
      buildid:
        type: string
        required: true
        description: BuildID of Firefox build
      buildid2:
        type: string
        required: true
        description: BuildID of build
      firefox-version:
        type: string
        required: true
        description: Firefox version (e.g. 124.0)
      app-version2:
        type: string
        required: true
        description: App version 2 (e.g. 12.0.0)
      release-note-url:
        type: string
        default: https://blog.ablaze.one/category/ablaze/ablaze-project/floorp/
        required: false
        description: Release Note URL

jobs:
  deliver-rc-updates:
    runs-on: ubuntu-22.04

    env:
      RELEASE_NOTE_URL: ${{ inputs.release-note-url }}
      APP_VERSION2: ${{ inputs.app-version2 }}
    steps:
      - name: Show parameters
        run: |
          echo Windows MAR : ${{ inputs.win-mar-url }}
          echo Linux   MAR : ${{ inputs.linux-mar-url }}
          echo macOS   MAR : ${{ inputs.mac-mar-url }}
          echo App Version 2 : $APP_VERSION2
          echo BuildID   : ${{ inputs.buildid }}
          echo BuildID2  : ${{ inputs.buildid2 }}
          echo Firefox Ver    : ${{ inputs.firefox-version }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Prepare workspace
        run: mkdir -p ~/update_tmpfiles

      - name: Process Windows & Linux MAR
        run: |
          set -e

          process() {
            local OS=$1
            local ARCH=$2
            local URL=$3
            local OUT_ENV_PREFIX=$4   # e.g. WIN or LINUX

            cd ~/update_tmpfiles
            mkdir -p "$OS-$ARCH"
            cd "$OS-$ARCH"
            wget -nv "$URL" -O file.mar

            # size
            local SIZE
            SIZE=$(stat -c%s "file.mar")
            echo "${OUT_ENV_PREFIX}_SIZE=$SIZE" >> $GITHUB_ENV
          }

          process WINNT x86_64 '${{ inputs.win-mar-url }}' WIN
          process Linux x86_64 '${{ inputs.linux-mar-url }}' LINUX

      - name: Generate macOS env
        run: |
          wget -nv '${{ inputs.mac-mar-url }}' -O ~/update_tmpfiles/mac-file.mar
          echo "MAC_SIZE=$(stat -c%s ~/update_tmpfiles/mac-file.mar)" >> $GITHUB_ENV
          echo "BUILDID=${{ inputs.buildid }}" >> $GITHUB_ENV
          echo "BUILDID2=${{ inputs.buildid2 }}" >> $GITHUB_ENV
          echo "FIREFOX_VERSION=${{ inputs.firefox-version }}" >> $GITHUB_ENV

      - name: Create update.xml files
        run: |
          set -e
          make_xml () {
            local OS=$1
            local ARCH=$2
            local SIZE=$3
            local MAR_URL=$4

            update_xml=(
            '<?xml version="1.0" encoding="UTF-8"?>'
            '<updates>'
            "    <update type=\"minor\" displayVersion=\"${FIREFOX_VERSION}@${APP_VERSION2}\" appVersion=\"${FIREFOX_VERSION}\" platformVersion=\"${FIREFOX_VERSION}\" buildID=\"${BUILDID}\" appVersion2=\"${APP_VERSION2}\" buildID2=\"${BUILDID2}\" detailsURL=\"${RELEASE_NOTE_URL}\">"
            "        <patch type=\"complete\" URL=\"${MAR_URL}\" size=\"${SIZE}\"/>"
            '    </update>'
            '</updates>'
            )
            mkdir -p browser/rc/${OS}/${ARCH}
            : > browser/rc/${OS}/${ARCH}/update.xml
            for line in "${update_xml[@]}"; do echo "$line" >> browser/rc/${OS}/${ARCH}/update.xml ; done
          }

          make_xml WINNT x86_64 $WIN_SIZE '${{ inputs.win-mar-url }}'
          make_xml Linux x86_64 $LINUX_SIZE '${{ inputs.linux-mar-url }}'
          make_xml Darwin x86_64 $MAC_SIZE '${{ inputs.mac-mar-url }}'
          make_xml Darwin aarch64 $MAC_SIZE '${{ inputs.mac-mar-url }}'

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "🛈 変更がないためコミットをスキップします。"
            exit 0
          fi
          git commit -m "Update Floorp RC update.xml (${APP_VERSION2})"
          git pull -r
          git push origin
