# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: Update Floorp-Portable version
on:
  workflow_dispatch:
    inputs:
      display-version:
        description: 'Display version of the update'
        required: true
        type: string

jobs:
  update-latest-json:
    runs-on: ubuntu-latest
    steps:
      - name: Details
        run: |
          echo "Display version: ${{ github.event.inputs.display-version }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: get current version
        run: |
          echo "Getting current version"
          export CURRENT_VERSION=`cat ./browser-portable/latest.json | jq -r ".[].version" | head -1`
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

          if [[ "$CURRENT_VERSION" == "null" ]]; then
            false
          fi
    
      - name: Update latest.json
        run: |
          echo "Updating latest.json"
          echo "new version: ${{ github.event.inputs.display-version }}"
          echo "current version: ${{ env.CURRENT_VERSION }}"
          sed -i 's/${{ env.CURRENT_VERSION }}/${{ github.event.inputs.display-version }}/g' ./browser-portable/latest.json

      - name: Commit
        run: |
          git add .
          git commit -m "Update Floorp Portable version"
          git push

      - name: Waiting 5 seconds...
        run: |
          sleep 5

  upload:
    needs: ["update-latest-json"]
    uses: ./.github/workflows/upload.yml
    secrets:
      FTP_ADDR: ${{ secrets.FTP_ADDR }}
      FTP_USER: ${{ secrets.FTP_USER }}
      FTP_PASS: ${{ secrets.FTP_PASS }}
