on:
  push:
    branches: main
  workflow_call:
    secrets:
      FTP_ADDR:
        required: true
      FTP_USER:
        required: true
      FTP_PASS:
        required: true

name: Upload
jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Upload files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_ADDR }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        exclude: |
          **/.git*
          **/.git*/**
          LICENSE
          README.md
